USE db_pemilu_c1;

-- Dapil DPR RI + DPD (PKPU 6/2023)
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRRI-LPG-1','DPR_RI','LPG-1','Dapil Lampung I (DPR RI)',18,NULL,10) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRRI-LPG-1', 1801);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRRI-LPG-1', 1871);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRRI-LPG-1', 1809);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRRI-LPG-1', 1806);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRRI-LPG-1', 1810);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRRI-LPG-1', 1804);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRRI-LPG-1', 1813);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRRI-LPG-1', 1872);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRRI-LPG-2','DPR_RI','LPG-2','Dapil Lampung II (DPR RI)',18,NULL,10) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRRI-LPG-2', 1807);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRRI-LPG-2', 1802);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRRI-LPG-2', 1808);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRRI-LPG-2', 1805);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRRI-LPG-2', 1811);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRRI-LPG-2', 1812);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRRI-LPG-2', 1803);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPD-LPG','DPD','LPG','Dapil DPD RI Lampung',18,NULL,4) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi);

-- Dapil DPRD Provinsi (85 kursi)
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDPROV-LPG-1','DPRD_PROV','LPG-1','Dapil Lampung 1 (DPRD Provinsi)',18,NULL,11) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRDPROV-LPG-1', 1871);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDPROV-LPG-2','DPRD_PROV','LPG-2','Dapil Lampung 2 (DPRD Provinsi)',18,NULL,10) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRDPROV-LPG-2', 1801);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDPROV-LPG-3','DPRD_PROV','LPG-3','Dapil Lampung 3 (DPRD Provinsi)',18,NULL,11) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRDPROV-LPG-3', 1809);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRDPROV-LPG-3', 1810);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRDPROV-LPG-3', 1872);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDPROV-LPG-4','DPRD_PROV','LPG-4','Dapil Lampung 4 (DPRD Provinsi)',18,NULL,10) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRDPROV-LPG-4', 1806);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRDPROV-LPG-4', 1804);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRDPROV-LPG-4', 1813);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDPROV-LPG-5','DPRD_PROV','LPG-5','Dapil Lampung 5 (DPRD Provinsi)',18,NULL,11) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRDPROV-LPG-5', 1803);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRDPROV-LPG-5', 1808);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDPROV-LPG-6','DPRD_PROV','LPG-6','Dapil Lampung 6 (DPRD Provinsi)',18,NULL,10) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRDPROV-LPG-6', 1811);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRDPROV-LPG-6', 1805);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRDPROV-LPG-6', 1812);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDPROV-LPG-7','DPRD_PROV','LPG-7','Dapil Lampung 7 (DPRD Provinsi)',18,NULL,12) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRDPROV-LPG-7', 1802);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDPROV-LPG-8','DPRD_PROV','LPG-8','Dapil Lampung 8 (DPRD Provinsi)',18,NULL,10) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi);
INSERT IGNORE INTO dapil_kabupaten (dapil_id, kabupaten_id) VALUES ('DPRDPROV-LPG-8', 1807);

-- Dapil DPRD Kab/Kota (600 kursi)
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1801-1','DPRD_KABKOTA','1801-1','Dapil Lampung Selatan 1 (DPRD Kabupaten)',18,1801,6) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1801-1', 46);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1801-1', 47);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1801-2','DPRD_KABKOTA','1801-2','Dapil Lampung Selatan 2 (DPRD Kabupaten)',18,1801,7) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1801-2', 43);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1801-2', 48);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1801-2', 45);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1801-3','DPRD_KABKOTA','1801-3','Dapil Lampung Selatan 3 (DPRD Kabupaten)',18,1801,7) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1801-3', 50);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1801-3', 51);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1801-3', 49);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1801-3', 52);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1801-4','DPRD_KABKOTA','1801-4','Dapil Lampung Selatan 4 (DPRD Kabupaten)',18,1801,9) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1801-4', 36);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1801-5','DPRD_KABKOTA','1801-5','Dapil Lampung Selatan 5 (DPRD Kabupaten)',18,1801,6) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1801-5', 37);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1801-6','DPRD_KABKOTA','1801-6','Dapil Lampung Selatan 6 (DPRD Kabupaten)',18,1801,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1801-6', 38);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1801-6', 41);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1801-6', 39);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1801-7','DPRD_KABKOTA','1801-7','Dapil Lampung Selatan 7 (DPRD Kabupaten)',18,1801,7) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1801-7', 40);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1801-7', 44);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1801-7', 42);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1802-1','DPRD_KABKOTA','1802-1','Dapil Lampung Tengah 1 (DPRD Kabupaten)',18,1802,10) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-1', 85);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-1', 89);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-1', 91);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-1', 98);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-1', 90);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-1', 99);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1802-2','DPRD_KABKOTA','1802-2','Dapil Lampung Tengah 2 (DPRD Kabupaten)',18,1802,10) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-2', 100);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-2', 103);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-2', 97);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-2', 101);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-2', 104);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-2', 102);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1802-3','DPRD_KABKOTA','1802-3','Dapil Lampung Tengah 3 (DPRD Kabupaten)',18,1802,11) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-3', 82);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-3', 84);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-3', 88);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-3', 87);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-3', 86);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-3', 83);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1802-4','DPRD_KABKOTA','1802-4','Dapil Lampung Tengah 4 (DPRD Kabupaten)',18,1802,9) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-4', 77);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-4', 93);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-4', 79);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-4', 78);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-4', 80);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-4', 81);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1802-5','DPRD_KABKOTA','1802-5','Dapil Lampung Tengah 5 (DPRD Kabupaten)',18,1802,10) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-5', 92);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-5', 96);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-5', 95);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1802-5', 94);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1803-1','DPRD_KABKOTA','1803-1','Dapil Lampung Utara 1 (DPRD Kabupaten)',18,1803,6) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-1', 112);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-1', 113);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1803-2','DPRD_KABKOTA','1803-2','Dapil Lampung Utara 2 (DPRD Kabupaten)',18,1803,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-2', 114);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-2', 109);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-2', 111);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-2', 110);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1803-3','DPRD_KABKOTA','1803-3','Dapil Lampung Utara 3 (DPRD Kabupaten)',18,1803,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-3', 105);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-3', 107);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-3', 108);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-3', 106);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1803-4','DPRD_KABKOTA','1803-4','Dapil Lampung Utara 4 (DPRD Kabupaten)',18,1803,5) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-4', 120);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-4', 126);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-4', 127);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-4', 124);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-4', 123);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1803-5','DPRD_KABKOTA','1803-5','Dapil Lampung Utara 5 (DPRD Kabupaten)',18,1803,6) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-5', 125);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-5', 121);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-5', 122);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1803-6','DPRD_KABKOTA','1803-6','Dapil Lampung Utara 6 (DPRD Kabupaten)',18,1803,5) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-6', 118);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-6', 119);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1803-7','DPRD_KABKOTA','1803-7','Dapil Lampung Utara 7 (DPRD Kabupaten)',18,1803,7) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-7', 115);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-7', 116);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1803-7', 117);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1804-1','DPRD_KABKOTA','1804-1','Dapil Lampung Barat 1 (DPRD Kabupaten)',18,1804,9) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1804-1', 1);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1804-1', 2);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1804-1', 3);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1804-2','DPRD_KABKOTA','1804-2','Dapil Lampung Barat 2 (DPRD Kabupaten)',18,1804,5) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1804-2', 4);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1804-2', 7);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1804-2', 9);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1804-3','DPRD_KABKOTA','1804-3','Dapil Lampung Barat 3 (DPRD Kabupaten)',18,1804,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1804-3', 12);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1804-3', 5);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1804-3', 8);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1804-4','DPRD_KABKOTA','1804-4','Dapil Lampung Barat 4 (DPRD Kabupaten)',18,1804,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1804-4', 11);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1804-4', 13);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1804-4', 14);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1804-4', 15);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1804-5','DPRD_KABKOTA','1804-5','Dapil Lampung Barat 5 (DPRD Kabupaten)',18,1804,5) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1804-5', 6);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1804-5', 10);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1805-1','DPRD_KABKOTA','1805-1','Dapil Tulang Bawang 1 (DPRD Kabupaten)',18,1805,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1805-1', 180507);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1805-1', 180514);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1805-1', 180508);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1805-2','DPRD_KABKOTA','1805-2','Dapil Tulang Bawang 2 (DPRD Kabupaten)',18,1805,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1805-2', 180501);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1805-2', 180502);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1805-3','DPRD_KABKOTA','1805-3','Dapil Tulang Bawang 3 (DPRD Kabupaten)',18,1805,5) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1805-3', 180510);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1805-3', 180505);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1805-4','DPRD_KABKOTA','1805-4','Dapil Tulang Bawang 4 (DPRD Kabupaten)',18,1805,4) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1805-4', 180512);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1805-4', 180513);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1805-5','DPRD_KABKOTA','1805-5','Dapil Tulang Bawang 5 (DPRD Kabupaten)',18,1805,5) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1805-5', 180503);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1805-6','DPRD_KABKOTA','1805-6','Dapil Tulang Bawang 6 (DPRD Kabupaten)',18,1805,3) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1805-6', 180506);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1805-7','DPRD_KABKOTA','1805-7','Dapil Tulang Bawang 7 (DPRD Kabupaten)',18,1805,3) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1805-7', 180504);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1805-7', 180509);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1805-8','DPRD_KABKOTA','1805-8','Dapil Tulang Bawang 8 (DPRD Kabupaten)',18,1805,4) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1805-8', 180511);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1805-8', 180515);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1806-1','DPRD_KABKOTA','1806-1','Dapil Tanggamus 1 (DPRD Kabupaten)',18,1806,7) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-1', 19);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-1', 22);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-1', 21);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1806-2','DPRD_KABKOTA','1806-2','Dapil Tanggamus 2 (DPRD Kabupaten)',18,1806,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-2', 16);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-2', 17);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-2', 20);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-2', 18);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1806-3','DPRD_KABKOTA','1806-3','Dapil Tanggamus 3 (DPRD Kabupaten)',18,1806,7) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-3', 27);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-3', 28);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-3', 29);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1806-4','DPRD_KABKOTA','1806-4','Dapil Tanggamus 4 (DPRD Kabupaten)',18,1806,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-4', 23);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-4', 24);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-4', 25);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1806-5','DPRD_KABKOTA','1806-5','Dapil Tanggamus 5 (DPRD Kabupaten)',18,1806,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-5', 26);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-5', 30);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1806-6','DPRD_KABKOTA','1806-6','Dapil Tanggamus 6 (DPRD Kabupaten)',18,1806,7) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-6', 32);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-6', 33);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-6', 34);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-6', 31);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1806-6', 35);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1807-1','DPRD_KABKOTA','1807-1','Dapil Lampung Timur 1 (DPRD Kabupaten)',18,1807,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-1', 70);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-1', 75);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-1', 71);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-1', 76);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1807-2','DPRD_KABKOTA','1807-2','Dapil Lampung Timur 2 (DPRD Kabupaten)',18,1807,7) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-2', 62);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-2', 64);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-2', 65);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1807-3','DPRD_KABKOTA','1807-3','Dapil Lampung Timur 3 (DPRD Kabupaten)',18,1807,7) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-3', 67);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-3', 63);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-3', 69);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-3', 68);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1807-4','DPRD_KABKOTA','1807-4','Dapil Lampung Timur 4 (DPRD Kabupaten)',18,1807,7) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-4', 58);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-4', 66);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-4', 59);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-4', 61);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1807-5','DPRD_KABKOTA','1807-5','Dapil Lampung Timur 5 (DPRD Kabupaten)',18,1807,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-5', 56);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-5', 57);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-5', 60);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1807-6','DPRD_KABKOTA','1807-6','Dapil Lampung Timur 6 (DPRD Kabupaten)',18,1807,7) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-6', 55);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-6', 54);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-6', 53);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1807-7','DPRD_KABKOTA','1807-7','Dapil Lampung Timur 7 (DPRD Kabupaten)',18,1807,6) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-7', 73);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-7', 74);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1807-7', 72);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1808-1','DPRD_KABKOTA','1808-1','Dapil Way Kanan 1 (DPRD Kabupaten)',18,1808,9) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1808-1', 133);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1808-1', 135);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1808-1', 180815);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1808-2','DPRD_KABKOTA','1808-2','Dapil Way Kanan 2 (DPRD Kabupaten)',18,1808,7) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1808-2', 136);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1808-2', 134);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1808-2', 137);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1808-2', 138);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1808-3','DPRD_KABKOTA','1808-3','Dapil Way Kanan 3 (DPRD Kabupaten)',18,1808,9) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1808-3', 139);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1808-3', 140);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1808-3', 141);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1808-4','DPRD_KABKOTA','1808-4','Dapil Way Kanan 4 (DPRD Kabupaten)',18,1808,6) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1808-4', 129);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1808-4', 130);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1808-5','DPRD_KABKOTA','1808-5','Dapil Way Kanan 5 (DPRD Kabupaten)',18,1808,9) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1808-5', 131);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1808-5', 128);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1808-5', 132);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1809-1','DPRD_KABKOTA','1809-1','Dapil Pesawaran 1 (DPRD Kabupaten)',18,1809,9) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1809-1', 150);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1809-2','DPRD_KABKOTA','1809-2','Dapil Pesawaran 2 (DPRD Kabupaten)',18,1809,6) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1809-2', 151);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1809-3','DPRD_KABKOTA','1809-3','Dapil Pesawaran 3 (DPRD Kabupaten)',18,1809,5) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1809-3', 152);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1809-4','DPRD_KABKOTA','1809-4','Dapil Pesawaran 4 (DPRD Kabupaten)',18,1809,5) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1809-4', 142);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1809-4', 143);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1809-4', 146);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1809-5','DPRD_KABKOTA','1809-5','Dapil Pesawaran 5 (DPRD Kabupaten)',18,1809,6) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1809-5', 144);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1809-5', 145);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1809-6','DPRD_KABKOTA','1809-6','Dapil Pesawaran 6 (DPRD Kabupaten)',18,1809,9) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1809-6', 149);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1809-6', 147);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1809-6', 148);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1810-1','DPRD_KABKOTA','1810-1','Dapil Pringsewu 1 (DPRD Kabupaten)',18,1810,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1810-1', 157);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1810-2','DPRD_KABKOTA','1810-2','Dapil Pringsewu 2 (DPRD Kabupaten)',18,1810,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1810-2', 161);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1810-2', 159);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1810-3','DPRD_KABKOTA','1810-3','Dapil Pringsewu 3 (DPRD Kabupaten)',18,1810,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1810-3', 158);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1810-4','DPRD_KABKOTA','1810-4','Dapil Pringsewu 4 (DPRD Kabupaten)',18,1810,7) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1810-4', 154);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1810-4', 153);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1810-5','DPRD_KABKOTA','1810-5','Dapil Pringsewu 5 (DPRD Kabupaten)',18,1810,9) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1810-5', 155);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1810-5', 160);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1810-5', 156);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1811-1','DPRD_KABKOTA','1811-1','Dapil Mesuji 1 (DPRD Kabupaten)',18,1811,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1811-1', 166);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1811-1', 167);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1811-2','DPRD_KABKOTA','1811-2','Dapil Mesuji 2 (DPRD Kabupaten)',18,1811,3) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1811-2', 168);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1811-3','DPRD_KABKOTA','1811-3','Dapil Mesuji 3 (DPRD Kabupaten)',18,1811,6) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1811-3', 165);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1811-4','DPRD_KABKOTA','1811-4','Dapil Mesuji 4 (DPRD Kabupaten)',18,1811,6) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1811-4', 162);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1811-5','DPRD_KABKOTA','1811-5','Dapil Mesuji 5 (DPRD Kabupaten)',18,1811,7) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1811-5', 163);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1811-5', 164);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1812-1','DPRD_KABKOTA','1812-1','Dapil Tulang Bawang Barat 1 (DPRD Kabupaten)',18,1812,11) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1812-1', 171);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1812-2','DPRD_KABKOTA','1812-2','Dapil Tulang Bawang Barat 2 (DPRD Kabupaten)',18,1812,9) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1812-2', 170);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1812-2', 169);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1812-3','DPRD_KABKOTA','1812-3','Dapil Tulang Bawang Barat 3 (DPRD Kabupaten)',18,1812,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1812-3', 174);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1812-3', 173);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1812-3', 172);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1812-3', 175);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1812-4','DPRD_KABKOTA','1812-4','Dapil Tulang Bawang Barat 4 (DPRD Kabupaten)',18,1812,7) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1812-4', 176);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1812-4', 177);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1813-1','DPRD_KABKOTA','1813-1','Dapil Pesisir Barat 1 (DPRD Kabupaten)',18,1813,6) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1813-1', 183);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1813-1', 182);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1813-1', 184);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1813-2','DPRD_KABKOTA','1813-2','Dapil Pesisir Barat 2 (DPRD Kabupaten)',18,1813,7) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1813-2', 185);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1813-2', 186);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1813-3','DPRD_KABKOTA','1813-3','Dapil Pesisir Barat 3 (DPRD Kabupaten)',18,1813,6) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1813-3', 187);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1813-3', 188);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1813-4','DPRD_KABKOTA','1813-4','Dapil Pesisir Barat 4 (DPRD Kabupaten)',18,1813,6) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1813-4', 178);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1813-4', 179);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1813-4', 181);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1813-4', 180);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1871-1','DPRD_KABKOTA','1871-1','Dapil Bandar Lampung 1 (DPRD Kota)',18,1871,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-1', 191);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-1', 189);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-1', 196);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-1', 190);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1871-2','DPRD_KABKOTA','1871-2','Dapil Bandar Lampung 2 (DPRD Kota)',18,1871,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-2', 199);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-2', 194);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-2', 197);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-2', 198);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1871-3','DPRD_KABKOTA','1871-3','Dapil Bandar Lampung 3 (DPRD Kota)',18,1871,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-3', 203);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-3', 200);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-3', 201);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1871-4','DPRD_KABKOTA','1871-4','Dapil Bandar Lampung 4 (DPRD Kota)',18,1871,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-4', 202);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-4', 205);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-4', 208);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1871-5','DPRD_KABKOTA','1871-5','Dapil Bandar Lampung 5 (DPRD Kota)',18,1871,9) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-5', 206);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-5', 204);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-5', 207);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1871-6','DPRD_KABKOTA','1871-6','Dapil Bandar Lampung 6 (DPRD Kota)',18,1871,9) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-6', 193);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-6', 195);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1871-6', 192);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1872-1','DPRD_KABKOTA','1872-1','Dapil Metro 1 (DPRD Kota)',18,1872,8) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1872-1', 212);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1872-2','DPRD_KABKOTA','1872-2','Dapil Metro 2 (DPRD Kota)',18,1872,5) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1872-2', 213);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1872-3','DPRD_KABKOTA','1872-3','Dapil Metro 3 (DPRD Kota)',18,1872,6) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1872-3', 211);
INSERT INTO dapil (id, tingkat, kode, nama, provinsi_id, kabupaten_id, jml_kursi) VALUES ('DPRDKAB-1872-4','DPRD_KABKOTA','1872-4','Dapil Metro 4 (DPRD Kota)',18,1872,6) ON DUPLICATE KEY UPDATE nama=VALUES(nama), jml_kursi=VALUES(jml_kursi), kabupaten_id=VALUES(kabupaten_id);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1872-4', 210);
INSERT IGNORE INTO dapil_kecamatan (dapil_id, kecamatan_id) VALUES ('DPRDKAB-1872-4', 209);
